### PR TITLE
Switches to the new build system

### PR DESCRIPTION
**Pull request by ThadHouse**
WIP, and will fail on jenkins until it is updated.

### CODE REVIEW

**Comment by PeterJohnson** [comment]
@frcjenkins retest this please

**Comment by ThadHouse** [comment]
@frcjenkins retest this please

**Comment by ThadHouse** [comment]
Closes #82

**Comment by ThadHouse** [comment]
@frcjenkins retest this please

**Review by PeterJohnson — APPROVED** [review]

**Pull request merged**
